### ISSUE TITLE
BoundingBox format is not compatible with atlas.js

### ISSUE THREAD

**Issue by spicamelot** [arnaudleclerc/AzureMapsControl.Components#46]
**Describe the bug**
The Bounds camera options is not working. When the bounds are set, an unhandled exception occurs :

Error: Microsoft.JSInterop.JSException: The bounds specified are invalid: [[object Object]]
Error: The bounds specified are invalid: [[object Object]]
    at hg._generateSafeBounds (https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js:55:1159305)
    at hg.setCamera (https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js:55:1146383)
    at Function.b.setCameraOptions (https://localhost:44383/_content/AzureMapsControl.Components/azure-maps-control.min.js:4:7775)
    at https://localhost:44383/_framework/blazor.server.js:1:70368
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44383/_framework/blazor.server.js:1:70334)
    at https://localhost:44383/_framework/blazor.server.js:1:26441
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44383/_framework/blazor.server.js:1:26411)
    at e.processIncomingData (https://localhost:44383/_framework/blazor.server.js:1:24222)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AzureMapsControl.Components.Runtime.MapJsRuntime.InvokeVoidAsync(String identifier, Object[] args)
   at AzureMapsControl.Components.Map.Map.SetCameraOptionsAsync(Action`1 configure)
   at UrbanConnect.Pages.Map.UpdateMap() in C:\DEV\Blazor\Urban Connect\Pages\Map.razor:line 235

**To Reproduce**

On MapReady event, set a valid BoundingBox then set the bounds of the camera options :

                boundingBox = new AzureMapsControl.Components.Atlas.BoundingBox(8, 38, 10, 40);
                await urbanMap.SetCameraOptionsAsync(options =>
                {
                    options.Bounds = boundingBox;
                });

**Expected behavior**

In my case, markers are loaded dynamically according to a user-definable date range. I am trying to recenter and zoom the map according to the markers displayed.

**Screenshots**

Here is a deep dive of the Atlas.js when the error occurs :

![bounds-goWest](https://user-images.githubusercontent.com/67462386/118634130-7c381f00-b7d2-11eb-9c79-b15173e21b93.jpg)

As you can see, the AzureMapsControl.Components handle the bounds as an object with 4 properties (west, south, east, north), but the atlas.js is looking for an array with 4 values (or 6 if elevation is used).

When testing for Number(t[0]), the result is Nan. That leads to an unhandled exception.

**Additional context**
Beyond this bug, the BoundingBox class would benefit from exposing some of the native methods (https://docs.microsoft.com/en-us/javascript/api/azure-maps-control/atlas.data.boundingbox?view=azure-maps-typescript-latest), notably fromPositions(Position[]).

**Comment by arnaudleclerc** [comment]
Thanks for reporting that. I will work on a fix and publish it as soon as possible.

Adding the methods will require more work though, I won't include them in the hotfix, but I take note of it and will include them in a future version.

**Comment by arnaudleclerc** [comment]
A version 1.6.1-beta0001 has been published and should fix the issue. Could you please give it a shot and let me know if this works for you ?

**Comment by spicamelot** [comment]
Thanks ! 
Issue is fixed on 1.6.1-beta0001.

**Comment by arnaudleclerc** [comment]
Great, thanks for the feedback! I just published a stable 1.6.1 with this fix, so I will close this issue
