### ISSUE TITLE
Sample runtime failure Could not find 'azureMapsControl.Core.addMap' ('azureMapsControl' was undefined).

### ISSUE THREAD

**Issue by DavidThielen** [arnaudleclerc/AzureMapsControl.Components#88]
I've got the sample compiling and running. But on starting up it throws:
```
Microsoft.JSInterop.JSException: Could not find 'azureMapsControl.Core.addMap' ('azureMapsControl' was undefined).
Error: Could not find 'azureMapsControl.Core.addMap' ('azureMapsControl' was undefined).
    at https://localhost:7159/_framework/blazor.web.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7159/_framework/blazor.web.js:1:702)
    at b (https://localhost:7159/_framework/blazor.web.js:1:5445)
    at https://localhost:7159/_framework/blazor.web.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7159/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7159/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7159/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7159/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AzureMapsControl.Components.Runtime.MapJsRuntime.InvokeVoidAsync(String identifier, Object[] args) in C:\Git\AzureMapsControl.Components\src\AzureMapsControl.Components\Runtime\MapJsRuntime.cs:line 22
   at AzureMapsControl.Components.Map.AzureMap.OnAfterRenderAsync(Boolean firstRender) in C:\Git\AzureMapsControl.Components\src\AzureMapsControl.Components\Map\AzureMap.razor:line 429
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'MHbG-8tBm6VHLQaXUuHZm7aiZLgpGXhbD-f5DfYwShs'.
```

And this may be related. Visual Studio will not let me set a breakpoint in `AppMap.razor`. I can put it in `MapJsRuntime` which it calls. And on that break it shows `AppMap.razor` in the call stack. But can't set a breakpoint there.

Anyways, with this error, while the app runs, there's no map.

**Comment by arnaudleclerc** [comment]
Looks like you are missing the javascript component. My first would be that you only built the dotnet library itself, but not the typescript part. Can you please run `npm run build` and check if it makes any difference ?

Feel free to take a look at the development guidelines : https://github.com/arnaudleclerc/AzureMapsControl.Components/blob/develop/CONTRIBUTING.md#build-the-library

**Comment by DavidThielen** [comment]
Hi @arnaudleclerc 

I had run the steps in the doc but not `npm run build`. I ran that too and it was successful, but still the same error. Any other ideas?

I am running from Visual Studio.

thanks - dave
